# Generated by Django 5.1.6 on 2025-02-26 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('Short_description', models.CharField(blank=True, max_length=100, null=True)),
                ('content', models.TextField()),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('icon_Name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
