# Generated by Django 5.1.6 on 2025-02-26 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
